export var PI = Math.PI;
export var TAU = (PI * 2.0);
export var ITAU = (1.0 / TAU);
export var abs = Math.abs;
export var sin = Math.sin;
export var cos = Math.cos;
export var tan = Math.tan;
export var sqrt = Math.sqrt;
export var exp = Math.exp;
export var pow = Math.pow;
export var atan2 = Math.atan2;
export var atan = Math.atan;
export var atanh = Math.atanh;
export var acos = Math.acos;
export var acosh = Math.acosh;
//# sourceMappingURL=constants.js.map